### ISSUE TITLE
No country links on EITI dataset metadata

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#111]
Also missing category, year (unsure if previously included)

See: https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-trinidad-and-tobago

![image](https://user-images.githubusercontent.com/19787025/27441909-d7df41a8-573c-11e7-8d22-2c841502005f.png)

**Comment by mattfullerton** [comment]
This was fixed in https://github.com/derilinx/ckanext-nrgi-published/commit/5c5dbf7f8dd4abb5666942a46b551b771444fb81

We're rerunning the EITI import shortly to fill in the fields (CKAN silently drops extra fields that aren't in the schema, so the import lost those fields when there was no schema applied)
