### ISSUE TITLE
Cannot upload new file for dataset to staging

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#122]
I am getting an error when:

1) Trying to download the Latin America xlsx file (404 error)
2) Trying to upload a new file in place of what is there ("Server error" page when remove old dataset, upload new one and click "Update Resource") (Old file is still there after, repeat @ 1)

In the "Manage" tab for this dataset it is showing a file currently in place, but I cannot replace it and upload a new one.

See: https://staging.resourcedata.org/dataset/latin-america-extractive-industry-contextual-data/resource/113ea5f8-6881-41eb-9968-624d08b31958

**Comment by mattfullerton** [comment]
This was happening because the dataset was added when the schema was inactive, and now that its active again the update was throwing a validation error. To make matters worse CKAN was expecting a resource problem, but it wasn't a resource problem, so the error handling itself was crashing.

I've "fixed" this by filling in the missing metadata fields although many of the values are basically incorrect. This could be solved either by #120 (we would have an overarching dataset type with no special fields) or #101.

In addition its not really a file suitable for Datastore, so I've deleted that preview and added an Office Previewer instead.

https://staging.resourcedata.org/dataset/latin-america-extractive-industry-contextual-data/resource/113ea5f8-6881-41eb-9968-624d08b31958

**Comment by moman822** [comment]
The Office Previewer is great. Can this be automatically implemented for all XLS/XLSX type files? (not urgent).
