### ISSUE TITLE
Automatically remove datasets that don't have a question

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#137]

**Comment by mattfullerton** [comment]
As far as I can see, we don't have any documents without questions:
https://www.resourcedata.org/api/3/action/package_search?q=type:document&fq=-question:[%22%22%20TO%20*]

I think technically it could happen that if for some reason a fresh batch of questions was removed from the project and some documents would be left with no question, they would not be updated (because they have no question), leaving both the document and the not-wanted questions on the website. But I would say let's cross that bridge in the unlikely event that we come to it.
