### ISSUE TITLE
Show Complete Summary Data dataset at the top of the list

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#159]
Let's have the full dataset (https://www.resourcedata.org/dataset/eiti-complete-summary-table) be the first one shown when clicking "Datasets"

This otherwise does not stand out as an option.

**Comment by mattfullerton** [comment]
Not really possible without adding some "pin dataset" feature to CKAN which would not be worth the effort IMO. CKAN sorts by default by last updated at the top.

I do think there was a recent change where the summary dataset is in no way guaranteed to be the last one updated, I think previously it was. I've made a change in the import so that this is the case. This probably will lead to the result you want much of the time.

**Comment by mattfullerton** [comment]
Test after EITI import: http://li1665-139.members.linode.com/dataset
