### ISSUE TITLE
Exit facet search on Documents leads to Datasets

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#182]
Clicking this X takes you back to the datasets homepage

![image](https://user-images.githubusercontent.com/19787025/29924870-76799d6a-8e2c-11e7-89a1-813ae050e0b9.png)

**Comment by mattfullerton** [comment]
This was actually done before, then we updated CKAN and it got blown away. The fix is actually waiting to be merged into core CKAN:
https://github.com/ckan/ckan/pull/3643

See also #177

I'm inclined to concentrate on getting this PR merged rather than making another temp. fix to the copy of CKAN we use. Adding a label for this sort of problem.

**Comment by mattfullerton** [comment]
I have gone ahead and brought back the fix. I'm fairly confident the PR will be merged so this doesn't crop up again.
