### ISSUE TITLE
Resource data was down when container could not start

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#204]
## Why
We need to have no downtime when a website is deployed.

## What
- [ ] either have 2 instances of resourcedata running or find a way to keep the old container alive until the new one is started and becomes healthy

**Comment by adinuca** [comment]
There was a CPU spike when the container crashed.

**Comment by mattfullerton** [comment]
Some thoughts (just because I don't like to have issues lying around):

- We (Derilinx) shouldn't be deploying images that can't "boot"
- This may have happened recently as there was a lot of hectic activity trying to bring CKAN back into line
- We should be able to detect a problem like this on staging. An image should never be deployed to production without first testing (including visiting the site!) and production and staging environments should be identical, which I think they are

If you can find a way of "don't switch unless healthcheck = status(200)" or something similar, then that's really cool, but indeed it basically must mean running two instances at once. I don't think this is worth the effort as long as we all (especially the developers, at the moment mostly me) follow the basic points above.
