### ISSUE TITLE
Different data on EITI API vs. CSV download

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#220]
I am finding that the data available through the API is inconsistent with the data I get from the CSV download, with the CSV having more recently updated data.

If I download the data from the url on [this page](https://www.resourcedata.org/dataset/eiti-complete-summary-table/resource/4e4462a5-6029-4ae3-a4cc-66ad6ccc6d70): https://www.resourcedata.org/dataset/7dd3c8b6-9256-4e34-9360-1519efd87407/resource/4e4462a5-6029-4ae3-a4cc-66ad6ccc6d70/download/revenues-received-by-government-agencies.csv

...I get 6411 rows of data with a most recent timestamp of: `2018-02-28T07:01:31`

If I download using the following API query (found under the API button on the same page): https://www.resourcedata.org/api/3/action/datastore_search?resource_id=4e4462a5-6029-4ae3-a4cc-66ad6ccc6d70&limit=20000

...I get 6383 rows of data with a most recent timestamp of: `2018-02-23T07:01:31`

**Comment by moman822** [comment]
Additional comment: the data on the data preview on the same page appears to mirror the API data.

**Comment by moman822** [comment]
These now appear to be matching. Is there a significant time lag when data gets on the API db vs. wherever it is stored as CSV? I would say it was at least 1 week I saw the discrepancy.

**Comment by EricSoroos** [comment]
* The API is working off of the datastore data, which is pulled from the CSV resource after updating and pushed into the datastore by datapusher. 
* Any lag should be small, but would depend on the load on the system from other CSVs being uploaded at the same time. If there was a persistent difference, it's likely that the datapusher encountered a transient error and didn't upload that version of the CSV. 
* We've dramatically cut down the number and frequency of redundant pushes of the CSV, so it's more likely that the datapusher would run to completion. 

I believe that this has been fixed by the changes to the harvester. If you see this again, please reopen the issue.
