### ISSUE TITLE
Pinwheel of death for datasets

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#24]
## Why

Several datasets have an eternal pinwheel instead of showing data. For example: 

![image](https://cloud.githubusercontent.com/assets/1101585/25453357/a26f9ec8-2a96-11e7-9cc9-f7c7bfe89b23.png)
 
http://resourcedata.org/dataset/eiti-summary-data-table-for-timor-leste/resource/aebd7d19-42e6-4749-934b-0b4236baaa3c

**Comment by iprunache** [comment]
Same root cause as #23 .

**Comment by anderspeders** [comment]
Thanks,

Matt – it would be great if you could share a status on these issues tomorrow.

**Comment by mattfullerton** [comment]
See #23 - we should rename that issue and close this one

**Comment by mattfullerton** [comment]
@anderspeders Although that link won't work now because the script replaces the file resources with new ones, the resource files (if you back up to http://resourcedata.org/dataset/eiti-summary-data-table-for-timor-leste) are there and work - no spinning wheel of death ;-)

Indeed there is the problem you mention that one file is empty. Should we update the scripts to just not push a resource when there is nothing in it? Or is it good to explicitly show that there is no data on that in this way?

**Comment by anderspeders** [comment]
I think the best  option would be to not push a resource if it is empty. Right?

**Comment by mattfullerton** [comment]
Sounds good to me; will do

**Comment by mattfullerton** [comment]
Closing in favour of a renamed #23
