### ISSUE TITLE
Accessing dataset in Japanese triggers a server error

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#250]
## Why
Server Error is displayed every time a user accesses a dataset with a browser that has the language set to Japanese .

## What
- [ ] Datasets are displayed correctly for users whose browsers have the language set to Japanese .

## Notes
Example dataset : https://www.resourcedata.org/ja/dataset/64f75b05-9828-40c5-9cd5-f07f01cfb85a/resource/19f6eab0-03b4-4cda-87a7-38415f22d46a

**Comment by EricSoroos** [comment]
Do you have an error trace for this?

**Comment by adinuca** [comment]
I have attached the logs from Papertrail:
[rd_japan_error.log](https://github.com/NRGI/resourcedata.org/files/2548315/rd_japan_error.log)

**Comment by EricSoroos** [comment]
It appears that the error is pretty far in in this case. This is a core fanstatic routine that's called on every page, and it should fail with basically every non-latin characterset based language. We could possibly paper over this by decoding to utf-8, but the scope of what should be breaking is pretty large given the type of error. 

It looks like the datatables view translates one string (Hide/Unhide Columns), and it does fail on other non-latin languages (e.g. ru). Furthermore other strings that do translate correctly (Datasets) don't work on that page either. It also appears that this happens on other sites on CKAN 2.8.2.

For now, I'm disabling translation of that one string, since the rest of that interface is untranslated anyway.
