### ISSUE TITLE
Add country as metadata category in the left bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#27]
## Why

![image](https://cloud.githubusercontent.com/assets/1101585/25742118/f45dcdd8-315b-11e7-9108-bcce0408c314.png)

I think this should be done for datasets across all organizations.

**Comment by mattfullerton** [comment]
This is done on staging: http://li1665-139.members.linode.com/organization/nrgi

We are missing the countries because I only just recently restored the requirement for countries in the metadata (linked to #25)

Would you like to comment on what fields you would/would not like there in general (and if you like, what order) as until now it was not customized (for example "Organization" appears as a facet under the organization listing, which is a bit silly).
