### ISSUE TITLE
EITI automatic harvest to Energydata.info

### ISSUE THREAD

**Issue by jodiegardiner** [NRGI/resourcedata.org#270]
Set up automatic harvesting of the EITI csv file(s?) to the Energydata platform.

Thought I'd make an issue to get the ball rolling a bit faster on this one.  This should be really simple - ckan to ckan harvesters are usually relatively painless.

Just checking in the first instance with you Tommy that there aren't any other considerations beyond a straightforward copy of the data. Further, if you could identify exactly what should be grabbed that would be a good initial step too.

If you'd rather have a call to discuss then I'd be happy to do that too of course.

**Comment by deirdrelee** [comment]
Complete: https://energydata.info/dataset/eiti-complete-summary-table

There is a job running every night to update the dataset if there are changes. The dataset is updated about once a month on resourcedata.org but the energydata.info job runs nightly so that there is only a short delay between update on the host and that being reflected on energydata.info.
