### ISSUE TITLE
Changing sidebar filters to dropdown menus + enable multiple selection

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#61]
From a user testing the application.

Are dropdown menus possible?

Are datasets tagged with more than one filterable variable per category? If not then I think this would be unnecessary.

![image](https://cloud.githubusercontent.com/assets/19787025/26123497/1af13318-3a49-11e7-8238-4980320c6357.png)

**Comment by anderspeders** [comment]
My understanding is that CKAN does not offer drop downs, but Matt can confirm this.

**Comment by mattfullerton** [comment]
Actually its just a UI change. A big one, but just a change. The down side (apart from the effort required) is that its multiple clicks - first select the fields and then click "update" or so forth vs. one click (albeit then multiple clicks to build up a multiple selection) on a facet.

The bigger issue however is that I would expect from a multiselect dropdown a "OR" like behavior: give me all the datasets that match ANY of these. And CKAN's facets are AND/sub-filters.

Overall I feel like we would be better served by an expanded resource search page that also searches datasets and allows field selection in drop downs and free text fields as appropriate. This is something to consider as described in issue #29 

If you really, really want this, then leave the issue open and I will do it. Otherwise please close and lets keep discuss of the best search modality in #29
