### ISSUE TITLE
Generate email alert when new data is added to EITI datasets? 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#83]
## Why

As a user I would like to be alerted when new EITI data becomes available - for example when an additional year [YYYY] for a country is loaded. 

Are there examples of how this can be done?

**Comment by mattfullerton** [comment]
When you say "a country" does that mean the user is typically interested in a limited set of countries? In that case they can just "follow" the dataset.

However, I strongly suspect if they do, they will get a notification every time we run the import even when no new data is there. I will open a sep. issue for that because its also not ideal that resources are being replaced and resource URLs keep changing on every import.

cf. #77 @iprunache

**Comment by mattfullerton** [comment]
Closing this as following EITI datasets is now a feasible option (#88)
