### ISSUE TITLE
Remove file explorer for XLS files, others

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#90]
Excecl files won't dispaly in this data preview window. Can we restrict it from showing up on this page?

Alternatively, we could remove the entire option for files that aren't supported in the preview.

Link: https://www.resourcedata.org/dataset/peru-extractive-industry-contextual-data1

![image](https://user-images.githubusercontent.com/19787025/27043499-4bfbca66-4f68-11e7-9bcd-f1751bb9a242.png)

**Comment by mattfullerton** [comment]
XLS(X) should in general be supported. But that preview, whether via the jsondataproxy (when the resource isn't uploaded to the datastore, as hadn't been attempted in this case, probably because it was uploaded before Vitamin added it) or via datastore, is only designed for simple tabular data. Looking at the Excel file this is not the case so the preview is not suitable in this case.

To delete it, edit the views:
https://www.resourcedata.org/dataset/peru-extractive-industry-contextual-data1/resource/7916965b-4e84-4f12-9f66-c19a607822e8/views

And delete it.

I've done it this time :smile:
